### ISSUE TITLE
The legend does not display correctly.

### ISSUE THREAD

**Issue by zhongjingjogy** [pabristow/svg_plot#3]
Hi,

I have two kinds of data, one of which should be plotted with dots and the other should be plotted with solid lines.

I try to modify the example to have the such an effect, but it seems that the legends do not display correctly.

I wonder whether there is a way to fix it.

The code comes as following,
```
/*! \file 2d_bezier.cpp
  \brief Simple 2D plot using bezier curves.
  \author Jacob Voytko and Paul A. Bristow
  \date 2007
*/

// Copyright (C) Jacob Voytko 2007
// Copyright Paul A. Bristow 2009

// Use, modification and distribution are subject to the
// Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt
// or copy at http://www.boost.org/LICENSE_1_0.txt)

#include <boost/svg_plot/svg_2d_plot.hpp>
using namespace boost::svg;

#include <map>
  using std::map;
#include <cmath>
  using std::sin;
  using std::cos;

double f(double x)
{
  return sin(x);
}

double g(double x)
{
  return cos(x);
}

int main()
{
  map<double, double> data1, data2;

  double inter = 3.14159265 / 8.;

  for(double i=0; i<=10.; i+=inter)
  {
    data1[i] = f(i);
    data2[i] = g(i);
  }

  svg_2d_plot my_plot;

  // Size/scale settings.
  my_plot.size(700, 500)
    .x_range(-.5, 10.5)
    .y_range(-1.1, 1.1);

  // Text settings.
  my_plot.title("Plot of sin and cos functions")
    .title_font_size(29)
    .x_label("X Axis Units")
    .y_major_labels_side(-1)
    .y_major_grid_on(true);

  // Commands.
  my_plot.legend_on(true)
    .plot_window_on(true)
    .x_label_on(true);

  // Color settings.
  my_plot.background_color(svg_color(67, 111, 69))
    .legend_background_color(svg_color(207, 202,167))
    .legend_border_color(svg_color(102, 102, 84))
    .plot_background_color(svg_color(136, 188, 126))
    .title_color(white)
    .y_major_grid_color(black);

  // X axis settings.
  my_plot.x_major_interval(2)
    .x_major_tick_length(14)
    .x_major_tick_width(1)
    .x_minor_tick_length(7)
    .x_minor_tick_width(1)
    .x_num_minor_ticks(3)

  // Y axis settings.
    .y_major_interval(25)
    .y_num_minor_ticks(5);

  // legend settings.
  my_plot.legend_title_font_size(15);

  my_plot.plot(data1, "Sin(x)").line_on(true).line_width(5.0)
    .shape(circlet).size(6).fill_color(yellow);

  my_plot.plot(data2, "Series 1").stroke_color(blue);

  // Note the slightly smoother curve for the bezier_on compared to the line_on options.

  my_plot.write("./2d_bezier.svg");

  return 0;
} // int main()

```
![example](https://user-images.githubusercontent.com/9261231/43270937-d7b0c9be-9128-11e8-807e-235b428dd4d0.jpg)

**Comment by pabristow** [comment]
You are correct, as I have realised recently -  I have introduced a bug ☹  (in trying to fix other buglets).

I have tried to make a fix for this just committed to the *develop* branch

https://github.com/pabristow/svg_plot/commit/2e5f12d1da690838c607ebc7e67b5413ec2b4021

and this works for me on this example.

Perhaps you would like to try this for you plot and tell me if it fixes it for you.

Sorry – and thanks for reporting this 2d_bezier.cpp example.

Paul

PS I am actively working on improving this, so tell me of other bad features.

**Comment by zhongjingjogy** [comment]
Hi Paul,

I have test the [latest commits](https://github.com/pabristow/svg_plot/commit/2e5f12d1da690838c607ebc7e67b5413ec2b4021). I am afraid that the result had not been improved yet.

I would like to repeat the problem about this issue: I intend to plot a line without dots (solid line), but in the legend `Sin(x)` is denoted with black point, which I thought should be a solid line.

PS: I have improved the code in order to produce what I expect.
```
my_plot.plot(data1, "Sin(x)").line_on(true).line_width(5.0).fill_color(yellow);
my_plot.plot(data2, "Series 1").stroke_color(blue);
```

Best wishes!
Jing

**Comment by zhongjingjogy** [comment]
I had come across the examples in the repository, and I became a bit confused about how the legends are being designed. As it is shown in the example, the plots are plotted as scatter but there are lines in the legends. I wonder if the solid lines in the legends are used for guiding the markers to the labels. Is it? If that is true, I would like to recommend not using such a design, because it might be confusing when there are too much dots and lines in the plot.

PS: I am currently using the [gnum/plot](https://github.com/gonum/plot), but I have a project written in C++. I have been tired of wrapping everything with `cgo` and then use them in golang.  I think your work is really awesome, and I really appreciate much your project for providing a feasible way to plot things to `svg`.

![image](https://user-images.githubusercontent.com/9261231/43297377-93910d6a-9183-11e8-938a-0dfae926219b.png)

**Comment by pabristow** [comment]
OK, you are right about this, if there are only point markers and no joining lines used, then the legend should not show them,

and similarly if there are no markers, then these should not be shown.

Only if there are lines joining the points *and* markers should they both be shown in the legend.

And there should be a line joining the sin(x) points too.  I’ll produce a new example and check that all three options (line, markers, and line and markers) are shown in the legend.

I’ll try to fix this today(-ish).

I’m also trying to improve the docs which are a bit too computer-generated.  It proves rather difficult to describe the hundreds of possible options.

Thanks

Paul


PS I’m glad you are finding it useful – back-ending onto a C++ is exactly what I found it useful for.  (It should also be possible compress the SVG images so that the bandwidth for continuous updating is very small).

**Comment by pabristow** [comment]
I’ve had another try at fixing this with a new example using all the options.

I hope this meets your needs better.

Note that you need to explicitly use

.shape(none)

to avoid a default that puts a marker point on each data point (messy if you have hundreds of them).

I’m not sure if this default is the right policy but might have some implications for existing plots.

Paul

**Comment by zhongjingjogy** [comment]
Congratulations!

I would like to say it works!  

Thank you so much for quick and positive responses!

![image](https://user-images.githubusercontent.com/9261231/43351823-d419de76-924a-11e8-8cd7-68c9a27e8657.png)

PS
Last but not least I would like to kindly give one of my suggestions on the legend. The following is figure from famous plotting library,`matplotlib`, in `python`. The way that they arrange the legends for lines with symbols is to place the symbol on the line in the legend.  And they would lay the labels and the symbols on two columns and then align centering.

I would say you might want to keep this as a feature of `svg_plot`. That would also be great!

Best wishes!

![image](https://user-images.githubusercontent.com/9261231/43351866-76b93bcc-924b-11e8-91dd-6a3a160ef522.png)
