### ISSUE TITLE
Some markers are not sensitive to the size setting.

### ISSUE THREAD

**Issue by zhongjingjogy** [pabristow/svg_plot#5]
I have tried to scale the marker, but it seems that some markers are not sensitive to the size setting. In the figure, all the scatter lines have been plotted with following setting. Unfortunately, the asterisk and upper-triangle are not able to the scaled.

```
my_plot.plot(expdata, std::string("exp-") + std::to_string(i)).shape(shapes[i]).stroke_color(svg_colors[i]).size(20.0);
```

![image](https://user-images.githubusercontent.com/9261231/43624675-8a66ee88-971b-11e8-9270-28884cc2830d.png)

**Comment by pabristow** [comment]
Correct – and I am working on this right now (and have nearly fixed it).

Some of the symbols are generated using symbols (star diamond, any Unicode symbol like letters and Greek) whereas the rest are set using SVG circle, square and ellipse.

Sorry

Paul

**Comment by zhongjingjogy** [comment]
Great!

I am working on markers with Positive Polygon. I invent some utilities which can draw, triangle, square,  pentagon and hexagon. Such markers can also be rotated to some degree.

This is interesting! If you are interested in this implementation, I would like to share it with you.

```
struct HackedPoint {
	double cx, cy;
};

HackedPoint custom_rotate_point(HackedPoint &origin, HackedPoint &point, double theta) {

	HackedPoint apoint;
	apoint.cx = cos(theta)*(point.cx-origin.cx) - sin(theta)*(point.cy-origin.cy) + origin.cx;

	apoint.cy = sin(theta)*(point.cx-origin.cx) + cos(theta)*(point.cy-origin.cy) + origin.cy;

	return apoint;
}

void DrawPositivePolygon(int nedge, double size, boost::svg::g_element& g_ptr, double x, double y, bool rotated) {
  double r = size;
  int n = nedge;
  HackedPoint origin;
  origin.cx = 0.0;
  origin.cy = 0.0;
  HackedPoint point;
  point.cx = 0.0;
  point.cy = r;
  double theta0 = rotated ? 3.1415*2.0/double(n)/2.0: 0.0;
  HackedPoint oldpoint = custom_rotate_point(origin, point, theta0);
  point = oldpoint;
  for(int j = 1; j <= n+1; j++) {
    HackedPoint apoint = custom_rotate_point(origin, point, 3.140*2.0/double(n)*double(j));
    g_ptr.line(x + oldpoint.cx, y + oldpoint.cy, x + apoint.cx, y + apoint.cy);
    oldpoint = apoint;
  }
}
```

**Comment by zhongjingjogy** [comment]
It works well, but using polygon might be the best choice!

![image](https://user-images.githubusercontent.com/9261231/43637343-5483717a-9747-11e8-922b-1166c5619489.png)

```

struct HackedPoint {
	double cx, cy;
};

HackedPoint custom_rotate_point(HackedPoint &origin, HackedPoint &point, double theta) {

	HackedPoint apoint;
	apoint.cx = cos(theta)*(point.cx-origin.cx) - sin(theta)*(point.cy-origin.cy) + origin.cx;

	apoint.cy = sin(theta)*(point.cx-origin.cx) + cos(theta)*(point.cy-origin.cy) + origin.cy;

	return apoint;
}

void DrawPositivePolygon(int nedge, double size, boost::svg::g_element& g_ptr, double x, double y, bool rotated) {
  double r = size;
  int n = nedge;
  HackedPoint origin;
  origin.cx = 0.0;
  origin.cy = 0.0;
  HackedPoint point;
  point.cx = 0.0;
  point.cy = r;
  double theta0 = rotated ? 3.1415926*2.0/double(n)/2.0: 0.0;
  HackedPoint oldpoint = custom_rotate_point(origin, point, theta0);
  point = oldpoint;
  boost::svg::polygon_element& pg_ptr = g_ptr.polygon(x + point.cx, y + point.cy, true);
  // std::cout << "oldpoint: " << oldpoint.cx << ", " << oldpoint.cy << "\n";
  for(int j = 1; j <= n; j++) {
    HackedPoint apoint = custom_rotate_point(origin, point, 3.1415926*2.0/double(n)*double(j));
    // std::cout << apoint.cx << ", " << apoint.cy << "\n";
    // g_ptr.line(x + oldpoint.cx, y + oldpoint.cy, x + apoint.cx, y + apoint.cy);
    pg_ptr = pg_ptr.P(x + apoint.cx, y + apoint.cy);
    oldpoint = apoint;
  }
}
```

**Comment by pabristow** [comment]
You can have lots of fun with SVG ;-)

I considered this but concluded that it was easier to use Unicode symbols.  It makes the SVG smaller and pushes the rendering onto the browser.

I am considering using Unicode symbols circles etc for everything

https://www.w3schools.com/charsets/ref_utf_geometric.asp

http://www.fileformat.info/info/unicode/char/2b22/index.htm  black hexagon

http://www.fileformat.info/info/unicode/char/2B21/index.htm  white hexagon  (outline black)

rotation is still possible.

So I’m not going there.

Paul

**Comment by zhongjingjogy** [comment]
That is OK. I wonder whether the Unicode symbols can be scaled according to the size parameters. If it works, Unicode symbols might be much more promising.

**Comment by pabristow** [comment]
Unicode symbols can be scaled, but the code in master does not do this correctly at present.

I am working on this.
