### ISSUE TITLE
Possible option to turn off the zero xaxis and zero yaxis.

### ISSUE THREAD

**Issue by zhongjingjogy** [pabristow/svg_plot#7]
It seems that the zero xaxis and zero yaxis are plotted by default and I have been spent some time on finding the switch to turn them off. I would like to ask you from some hints and advice.

Thanks!

![image](https://user-images.githubusercontent.com/9261231/43625018-3704d410-971d-11e8-98b3-f08cf17dd331.png)

**Comment by pabristow** [comment]
1.  svg_2d_plot<file:///I:\modular-boost\libs\svg_plot\doc\html\boost\svg\svg_2d_plot.html> & x_axis_on(bool is);
If set true, draw a horizontal X-axis line.

and similarly y axis.


1.  svg_2d_plot<file:///I:\modular-boost\libs\svg_plot\doc\html\boost\svg\svg_2d_plot.html> & plot_window_on(bool cmd);
Set true if a plot window is wanted (or false if the whole image is to be used).

might also be what you want, or set the border to match the background (white on white ;-)

**Comment by zhongjingjogy** [comment]
Oh, I see!

Maybe I should spend more time on the documentation rather the source code! Thank you some much, and it is solved.

![image](https://user-images.githubusercontent.com/9261231/43637984-b2c45bd0-9749-11e8-8a48-f26dd24e0b10.png)

**Comment by pabristow** [comment]
Very pretty (though the axes tick values are a bit odd – I’d make the y-major interval 0.1 and the x-major 20  or 50)


svg_2d_plot & x_major_interval(double inter);
Set the interval between X-axis major ticks.
