### ISSUE TITLE
Layer of lines are not ordered by the order that they are plotted.

### ISSUE THREAD

**Issue by zhongjingjogy** [pabristow/svg_plot#8]
I have a plot with two kinds of series: lines and scatters. I try to plot them in different order.

1. lines -> scatters
2. scatters -> lines

But the two operations do not make a difference.

Generally, the layers of the items plotted before should be placed under those plotted after. 

I wonder if this is a design of the plot in  svg_plot, where the plot with markers always display on prior layers.

![image](https://user-images.githubusercontent.com/9261231/43672234-4fefc98e-97dc-11e8-9399-1205e15a9a1b.png)

**Comment by pabristow** [comment]
Yes - I think that this is ‘a feature not a bug’  ;-)

It might be possible to make this configurable but I’d need to think about it.

Perhaps using transparency would help show both?  But this was not something in the original design.

Or making the point markers a bit smaller?

Nice logo – I will try to make this a proper feature, extracting from an SVG file.  Would be useful for watermark (draft, confidential…) with high transparency.

Looks very convincing (and pretty) already.

**Comment by zhongjingjogy** [comment]
I found it. It is about the `document_ids_`. The browser renders the svg file according to the position that the elements exist in the svg file. In svg_plot, the elements are serialized according to the sequence of  `document_ids_`. 

As such an sequence is hard-coded, things might not be easily solved without changing the design of the svg_plot. Additional records that collect the information of the order of elements being added might be provided.

**Comment by pabristow** [comment]
Correct.

You could hack this to change the order, I believe, if it is crucial to your display.
