### ISSUE TITLE
The solid lines are not smooth.

### ISSUE THREAD

**Issue by zhongjingjogy** [pabristow/svg_plot#9]
I tried to plot solid lines with svg_plot, but it seems that the solid lines are not smooth enough. I try to activate the `bezier_on` for the plot, but it seems that such an option does not make any difference.

```
my_plot.plot(data, "title").stroke_color(svg_colors[i]).shape(none).line_color(svg_colors[i]).bezier_on(true);
```

![image](https://user-images.githubusercontent.com/9261231/43752534-09431da6-9a34-11e8-8648-48a91f4e9061.png)

**Comment by zhongjingjogy** [comment]
I tried to plot the same data with the `Python` package, `matplotlib`, and it gives much better rendering result. I would think the plotting algorithm in the `svg_plot` might have to be improved. And I would like to have your comment.

![image](https://user-images.githubusercontent.com/9261231/43752980-170b5b5e-9a36-11e8-9bc9-289aa49c715a.png)

**Comment by zhongjingjogy** [comment]
It seems that it is problem about the precision of points for path in svg file.

```
<path d="M122,66.6 L122,66.6 L122,66.6 L123,66.6 L124,66.6 L124,66.6 L125,66.6 L125,66.6 L126,66.6 L126,66.6 L127,66.6 L128,66.6 L128,66.6 L129,66.6 L129,66.6 L130,66.6 L131,66.6 L131,66.6 L132 ..../>
```

Is the precision of the numeric value for path one digit? In that case, the precision of the original lines might have been lost.

**Comment by zhongjingjogy** [comment]
It is problem about precision of the data written by the svg_plot library. Problem might get solved by increasing the precision of the values. I think `svg_plot` has been good enough to plot 1D and 2D figures for a lot of applications. But it might be bit hard to be customized without modifying the source code.

![image](https://user-images.githubusercontent.com/9261231/43753996-12eb5d12-9a3b-11e8-9931-bdda2fb7945a.png)

**Comment by pabristow** [comment]
Simple, see

1. void coord_precision(int digits);
Set decimal digits to be output for X and Y coordinates.
Default stream precision 6 decimal digits is probably excessive.
4.1 Basic data types, integer or float in decimal or scientific (using e format). 3 or 4 probably enough if image size is under 1000 x 1000. This will reduce .svg file sizes significantly for curves represented with many data points.
For example, if a curve is shown using 100 points, reducing to precision(3) from 6 will reduce file size by 300 bytes. So a default of 3 is used in the default constructor above, but can be changed using this function. Used in svg.write below and so applies to all the entire svg document.
.coord_precision(4) should meet you requirement.

Also .bezier_on(true) works for some functions (and I think will work for yours).
